var Mitm = require("./src/MitmServer")

var mitm = new Mitm()
mitm.listen(4001, "127.0.0.1", ()=>{
	mitm.on("tunnel", (obj)=>{
		console.log("==============================================================================")
		console.log("==============================================================================")
		console.log("Tunnel status: " + obj.status + " port: " + obj.port + "  host : " + obj.host)
		console.log("==============================================================================")
		console.log("==============================================================================")
	})
	mitm.on('finish', (req, resp)=>{
		console.log("GOT AN EVENT FROM MITM", req.constructor.name, resp.constructor.name)
		console.log("==============================================================================")
		console.log("HTTP/"+req.httpVersion)
		console.log(req.method)
		console.log(req.url)
		console.log(req.headers)
		console.log(req.rawBody.toString())
		console.log("-----------------------------------------------------------------------------")
		console.log("HTTP/"+resp.httpVersion)
		console.log(resp.statusCode)
		console.log(resp.statusMessage)
		console.log(resp.headers)
		console.log(resp.rawBody.toString())
		console.log("-----------------------------------------------------------------------------")		
	})
})